on:
  workflow_dispatch:
  schedule:
    - cron: '45 * */7 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/ha1dy-2ib3et4o@cron
        with:
          token: ${{ secrets.token }}
